<a href="https://colab.research.google.com/github/loicPf/test_ia/blob/main/Exercice_de_Crash_Course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importer la librairie `numpy` et lui donne l'alias `np`.

In [2]:
import numpy as np

Importer l'outil `MinMaxScaler` qui se trouve dans la librairie `sklearn`, afin que vous puissiez l'utiliser pour mettre à l'échelle les données dans votre projet de Machine Learning.

In [3]:
from sklearn.preprocessing import MinMaxScaler

En utilisant `numpy`, générez un jeu de données aléatoire nommé `data` qui contient 10 observations, chacune avec 2 caractéristiques. Les valeurs des caractéristiques doivent être des nombres entiers entre 0 et 99 (inclus).

In [6]:
data = np.random.randint(0, 100, (10, 2))
data

array([[62,  8],
       [30, 81],
       [60, 67],
       [31, 70],
       [75, 24],
       [12, 45],
       [45, 89],
       [16, 56],
       [30, 89],
       [56,  2]])

In [27]:
scaler_model = MinMaxScaler()

In [8]:
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [29]:
scaler_model.fit(data)

MinMaxScaler()

*  `scaler_model` est l'objet que nous avons créé précédemment pour effectuer la mise à l'échelle.
*  `fit` est une méthode (fonction) de l'objet `MinMaxScaler`. C'est l'étape où le scaler calcule les informations nécessaires à la mise à l'échelle.
*  `data`: Ce sont les données d'entrée fournies à la méthode `fit`. Le scaler apprendra les valeurs minimales et maximales à partir de ces données.

Imaginez que vous souhaitiez mettre à l'échelle les notes d'examen pour qu'elles soient comprises entre 0 et 1. Vous auriez d'abord besoin de connaître les notes les plus basses et les plus élevées de la classe.

`scaler_model.fit(data)` est comme l'étape où vous trouvez ces notes les plus basses et les plus élevées. Le `scaler_model` "sait" maintenant comment mettre à l'échelle les données futures en fonction de ces valeurs apprises.

In [31]:
print(scaler_model.data_max_)

[75. 89.]


In [30]:
scaler_model.transform(data)

array([[0.79365079, 0.06896552],
       [0.28571429, 0.90804598],
       [0.76190476, 0.74712644],
       [0.3015873 , 0.7816092 ],
       [1.        , 0.25287356],
       [0.        , 0.49425287],
       [0.52380952, 1.        ],
       [0.06349206, 0.62068966],
       [0.28571429, 1.        ],
       [0.6984127 , 0.        ]])

Cette ligne prend vos données `data` et les transforme en appliquant la mise à l'échelle que le `scaler_model` a apprise précédemment. Les valeurs de chaque colonne dans `data` seront ajustées pour se situer dans la plage spécifiée lors de la création du `MinMaxScaler` (par défaut, entre 0 et 1).

In [11]:
scaler_model.fit_transform(data)

array([[0.79365079, 0.06896552],
       [0.28571429, 0.90804598],
       [0.76190476, 0.74712644],
       [0.3015873 , 0.7816092 ],
       [1.        , 0.25287356],
       [0.        , 0.49425287],
       [0.52380952, 1.        ],
       [0.06349206, 0.62068966],
       [0.28571429, 1.        ],
       [0.6984127 , 0.        ]])

C'est un moyen d'adapter le scaler à vos données et de les transformer en une seule fois, plutôt que de le faire en deux étapes distinctes. C'est plus efficace et couramment utilisé lorsque vous souhaitez mettre à l'échelle vos données immédiatement après que le scaler a appris les informations nécessaires.

In [12]:
import pandas as pd

Nous avons besoin d'un jeu de données plus grand pour notre projet. Comment utiliseriez-vous `numpy` pour créer un tableau appelé `mydata` avec 50 observations et 4 caractéristiques, où chaque caractéristique est un entier aléatoire entre 0 et 100 (inclus) ?

In [14]:
mydata = np.random.randint(0, 101, (50, 4))
mydata

array([[ 33,  97,  29,  87],
       [ 38,  45,  65,  32],
       [ 67,  36,  36,   9],
       [ 51,  33,   8,  65],
       [ 79,  15,  86,  77],
       [ 40,  97,  45,  81],
       [ 99,  84,  61,  74],
       [ 57,  54,  11,  46],
       [ 83,  13,  57,  85],
       [  1,  53,  93,  73],
       [ 20,   4,  45,  21],
       [ 28,  97,  44,  50],
       [  1,  62,   0,  75],
       [ 74,  69,  82,   9],
       [ 64,  93,  15,  10],
       [ 99,  26,  21,  66],
       [ 11,  64,  85,  37],
       [ 32,  67,  78,  88],
       [ 52,  42,  56,  64],
       [ 73,   4,  94,  52],
       [ 74,  33,  13,  27],
       [100,  84,  55,  36],
       [ 75,  70,  28,  34],
       [ 82,  42,   1,  21],
       [ 94,  84,  98,  36],
       [ 86,  27,  66,  46],
       [ 92,  20,  78,  81],
       [ 45,  16,   8,   1],
       [  4,  45,  31,  22],
       [ 17, 100,  90,  69],
       [ 88,  27,  14,  51],
       [ 28,  90,  42,  53],
       [ 53,  29,  46,  20],
       [ 59,  97,  89,  82],
       [ 21,  

In [15]:
df = pd.DataFrame(data=mydata, columns = ['f1', 'f2', 'f3', 'label'])

Cette ligne de code prend les données numériques de mydata et les organise dans un tableau structuré (le DataFrame) avec des colonnes nommées 'f1', 'f2', 'f3' et 'label'.

En d'autres termes, on donne des étiquettes aux différentes "catégories" de données contenues dans mydata.

Imaginez un tableur Excel : `mydata` serait les données brutes dans les cellules, et `df` serait le tableur complet avec des en-têtes de colonnes pour organiser et comprendre les données.

In [16]:
df

,f1,f2,f3,label
0,33,97,29,87
1,38,45,65,32
2,67,36,36,9
3,51,33,8,65
4,79,15,86,77
5,40,97,45,81
6,99,84,61,74
7,57,54,11,46
8,83,13,57,85
9,1,53,93,73


In [17]:
X = df[['f1', 'f2', 'f3']]

In [18]:
y = df['label']

In [19]:
from sklearn.model_selection import train_test_split

La fonction `train_test_split` est utilisée pour diviser un jeu de données en deux parties :

1.   **Un ensemble d'entraînement (training set)** : Utilisé pour entraîner le modèle de Machine Learning.
2.   **Un ensemble de test (test set)** : Utilisé pour évaluer les performances du modèle après son entraînement, sur des données qu'il n'a jamais vues auparavant.

Diviser les données est crucial pour éviter l'**overfitting** qui se produit lorsque le modèle apprend trop bien les données d'entraînement et ne parvient pas à généraliser aux nouvelles données. En testant le modèle sur un ensemble de données distinct, on obtient une meilleure estimation de ses performances réelles.

In [20]:
X_train, X_test, y__train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

1.  `X, y` sont les données d'entrée de la fonction.
  *  `X` représente généralement vos **caractéristiques** (les variables d'entrée utilisées pour faire des prédictions).
  *  `y` représente votre **variable cible** ou **étiquettes** (ce que vous essayez de prédire).
2.  `test_size=0.3` spécifie la proportion de données qui doit être allouée à l'ensemble de test. Dans ce cas, 30 % des données seront utilisées pour les tests et les 70 % restants seront utilisés pour l'entraînement.
3.  `random_state=101` garantit que les données sont divisées de la même manière chaque fois que le code est exécuté. Ceci est important pour la reproductibilité, afin d'obtenir des résultats cohérents lors de l'expérimentation avec votre modèle. Si vous ne définissez pas de `random_state`, la division sera différente à chaque fois, ce qui peut rendre difficile la comparaison des performances de votre modèle entre différentes exécutions.

Nous avons divisé nos données en `X_train`, `X_test`, `y_train` et `y_test`. Comment pouvons-nous déterminer le nombre d'observations et de caractéristiques présentes dans l'ensemble d'entraînement `X_train` ?

In [21]:
X_train.shape

(35, 3)

(35, 3)

Comment pouvons-nous déterminer le nombre d'observations et de caractéristiques présentes dans l'ensemble de test `X_test` ?

In [22]:
X_test.shape

(15, 3)

(15, 3)